name: Build and Deploy Documentation

on:
  push:
    branches: [main]  # Change to your primary branch
    paths:
      - 'scripts/**'
      - 'docs/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
          
          # Install project dependencies (add your project dependencies here)
          pip install ants nibabel numpy torch scikit-learn

      - name: Build documentation
        run: |
          cd docs
          make html
          touch .nojekyll 
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
